version: "3.9"

services:
  photoframe:
    container_name: photoframe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5001"          
    volumes:
      - ./Images:/app/WebServer/Images 
    environment:
      TZ: "Asia/Jerusalem"
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      QUALITY: "70"
    restart: unless-stopped
