
services:
  photoframe_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photoframe_backend
    command: python3 PhotoFrameServer.py
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./Images:/app/Images
      - ./settings.json:/app/settings.json
      - ./metadata.json:/app/metadata.json
      - ./users.json:/app/users.json
      - ./PhotoFrame.log:/app/PhotoFrame.log
    environment:
      - TZ=Asia/Jerusalem
