
services:
  photoframe_desktop:
    build:
      context: .
      dockerfile: Dockerfile.desktop
    container_name: photoframe_desktop
    restart: always
    volumes:
      - ./photoframe_settings.json:/app/photoframe_settings.json
      - ./icons:/app/icons  
    devices:
      - "/dev/fb0:/dev/fb0"
    environment:
      - DISPLAY=:0
    network_mode: host  # needed to access localhost backend from container
